steps:
  # Build the runtime image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID',
      '.'
    ]
    id: 'build-image'

  # Run component tests inside the container
  # Uses container's entrypoint which copies models before running command
  - name: 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID'
    args: ['python', '/app/tests/test_components.py']
    id: 'test-components'
    waitFor: ['build-image']
    secretEnv:
      - 'ALPACA_API_KEY'
      - 'ALPACA_SECRET_KEY'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - 'AGENT_ID=test-agent'
      - 'ALPACA_ACCOUNT_ID=5a7527ab-1c85-4c5e-8ed3-0aeb3f5d2ba8'
      - 'FMEL_DATASET=fmel'
      - 'FMEL_TABLE=decisions_v2'

  # Run integration tests
  - name: 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID'
    args: ['python', '/app/tests/test_integration.py']
    id: 'test-integration'
    waitFor: ['test-components']
    secretEnv:
      - 'ALPACA_API_KEY'
      - 'ALPACA_SECRET_KEY'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - 'AGENT_ID=test-agent'
      - 'ALPACA_ACCOUNT_ID=5a7527ab-1c85-4c5e-8ed3-0aeb3f5d2ba8'
      - 'SYMBOLS=BTC/USD'
      - 'FMEL_DATASET=fmel'
      - 'FMEL_TABLE=decisions_v2'

  # Tag as latest if tests pass (images: section handles push)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID', 'gcr.io/$PROJECT_ID/runtime:latest']
    id: 'tag-latest'
    waitFor: ['test-integration']

# Push both tagged images to registry
images:
  - 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/runtime:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/RUNTIME_BROKER_API_KEY/versions/latest
      env: 'ALPACA_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/RUNTIME_BROKER_SECRET_KEY/versions/latest
      env: 'ALPACA_SECRET_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
