steps:
  # Build the runtime image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID',
      '.'
    ]
    id: 'build-image'

  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID', 'gcr.io/$PROJECT_ID/runtime:latest']
    id: 'tag-latest'
    waitFor: ['build-image']

# Push both tagged images to registry
images:
  - 'gcr.io/$PROJECT_ID/runtime:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/runtime:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
